In [8]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import cv2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import MaxPooling2D

# Defining the model

In [9]:
model = Sequential()

model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(48,48,1)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax'))

# Implementing the Model

In [17]:
#load the trained model
model.load_weights('model.h5')

# dictionary mapping class labels with corresponding emotions
emotion_dict = {0: "Angry", 1: "Disgusted", 2: "Fearful", 3: "Happy", 4: "Neutral", 5: "Sad", 6: "Surprised"}

#live feed from camera
cap = cv2.VideoCapture(0)
while True:
    # Capture frame
    ret, frame = cap.read()
    if not ret:
        break;
        
    # Find haar cascade to draw bounding box around face
    facecasc = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = facecasc.detectMultiScale(gray,scaleFactor=1.3, minNeighbors=5)

    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y-50), (x+w, y+h+10), (255, 0, 0), 2)
        roi_gray = gray[y:y + h, x:x + w]
        cropped_img = np.expand_dims(np.expand_dims(cv2.resize(roi_gray, (48, 48)), -1), 0)
        prediction = model.predict(cropped_img)
        maxindex = int(np.argmax(prediction))
        cv2.putText(frame, emotion_dict[maxindex], (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
    
    print(prediction.ravel()) #print prediction vector
    cv2.imshow('Video', cv2.resize(frame,(500,500),interpolation = cv2.INTER_CUBIC))
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 63ms/step
[2.7473476e-14 0.0000000e+00 1.0000000e+00 0.0000000e+00 1.5695484e-20
 0.0000000e+00 0.0000000e+00]
1/1 [==============================] - 0s 30ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 33ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 30ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 33ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 29ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 35ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 29ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 26ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 27ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [==============================] - 0s 37ms/step
[0. 0. 0. 0. 1. 0. 0.]
1/1 [=======================